#!/usr/bin/env bash

set -eu

cd "${BASH_SOURCE[0]%/*}"

tmpdir=$(mktemp -d)
cleanup() { rm -rf "$tmpdir"; }
trap cleanup EXIT

fetch() {
    local url=$1 oname stat scode surl
    oname=${url##*/}
    stat=$(
        curl -sSL -C - -z "$oname" \
            -w '%{http_code}\t%{url_effective}' \
            ${UAGENT:+-A "$UAGENT"} \
            -o "$tmpdir/$oname" "$url"
    )
    read -r scode surl <<<"$stat"
    case $scode in
        200) mv "$tmpdir/$oname" "$oname" ;;
        304) ;;
        *)
            exec >&2
            echo "HTTP $scode : $surl"
            cat "$oname"
            return 1
            ;;
    esac
}

fetch https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt
fetch https://raw.githubusercontent.com/vim/vim/master/src/digraph.c
#fetch https://raw.githubusercontent.com/neovim/neovim/master/src/nvim/digraph.c

{
    cat <<-EOF
	# XCompose digraphs as defined by Vim/Nvim
	#
	# Generated by:
	#
	#   https://github.com/mkoskar/xcompose-vim
	#   > $(date -R)
	#
	# See also:
	#
	#   (vim/nvim) :help digraphs
	#   Compose(5)
	#   RFC1345 (Character Mnemonics and Character Sets)

	# The second character has a standard meaning:
	#
	#   Char name               Char    Meaning
	#   ---------               ----    -------
	#   Exclamation mark        !       Grave
	#   Apostrophe              '       Acute accent
	#   Greater-Than sign       >       Circumflex accent
	#   Question mark           ?       Tilde
	#   Hyphen-Minus            -       Macron
	#   Left parenthesis        (       Breve
	#   Full stop               .       Dot above
	#   Colon                   :       Diaeresis
	#   Comma                   ,       Cedilla
	#   Underline               _       Underline
	#   Solidus                 /       Stroke
	#   Quotation mark          "       Double acute accent
	#   Semicolon               ;       Ogonek
	#   Less-Than sign          <       Caron
	#   Zero                    0       Ring above
	#   Two                     2       Hook
	#   Nine                    9       Horn
	#
	#   Equals                  =       Cyrillic (= used as second char)
	#   Asterisk                *       Greek
	#   Percent sign            %       Greek/Cyrillic special
	#   Plus                    +       smalls: Arabic, capitals: Hebrew
	#   Three                   3       some Latin/Greek/Cyrillic letters
	#   Four                    4       Bopomofo
	#   Five                    5       Hiragana
	#   Six                     6       Katakana

	EOF
    ./compile
} >.XCompose-vim
